[project]
requires-python = ">=3.10"

[tool.poetry]
name = "enka-py"
version = "1.4.0"
description = "An async API wrapper for enka.network written in Python."
authors = ["seriaati <seria.ati@gmail.com>"]
license = "GNU GPL v3.0"
readme = "README.md"
repository = "https://github.com/seriaati/enka-py"
packages = [{include = "enka"}]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.9.1"
cachetools = "^5.3.2"
pydantic = "^2.5.3"
orjson = "^3.9.10"
aiofiles = "^23.2.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ruff = "^0.2.1"
git-cliff = "^1.4.0"
pre-commit = "^3.6.0"
pytest = "^7.4.4"
pytest-asyncio = "^0.23.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "E","W","C90","F","UP","B","SIM","I","N","TCH",
    "ANN","ASYNC","A","C4","EM","FA","ICN","G",
    "PIE","T20","ARG","ERA","LOG","PL","TRY"
]
ignore = [
    "E501","ANN401","ANN101","ANN102","ANN003",
    "PLR0913","PLR2004","PLR0917","PLR6301"
]
preview = true

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F403"]
"enka/models/*.py" = ["ALL"]
"example.py" = ["T201", "ERA001"]

[tool.ruff.lint.flake8-type-checking]
quote-annotations = true