name: Update Data

on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Use the required Python version

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run pytest
        run: poetry run pytest